apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare
data:
  config.yaml: |
    tunnel: ef31ed8e-866f-4872-969a-f6e3a44c269a
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      - hostname: n8n.jmake.space
        service: http://n8n.n8n.svc.cluster.local:80
      - hostname: photos.jmake.space
        service: http://192.168.1.132:2283
      - hostname: wiki.jmake.space
        service: http://wiki-bookstack.wiki.svc.cluster.local:80
      - service: http_status:404
